### ISSUE TITLE
Pagina de User Profile Settings

### ISSUE THREAD

**Issue by RaduPantelimon** [RaduPantelimon/CEAE#6]

**Comment by xiodine32** [comment]
Would be great for administrators to view / modify parameters / view details / delete registered users. I've restyled with the latest commit -
 https://github.com/RaduPantelimon/CEAE/commit/291eea3e80e02a20295573b7603b38ad9e039865

**Comment by RaduPantelimon** [comment]
Added Statistics Section to this page + excel export button
