### ISSUE TITLE
Delete Answer Error

### ISSUE THREAD

**Issue by buletevlad** [RaduPantelimon/CEAE#9]
probably still connected to one or more questions

![rares_eroare stergere answe2r](https://cloud.githubusercontent.com/assets/16018758/26330674/c5f86112-3f55-11e7-8d0e-a42a7ee801d5.JPG)
![rares_eroare stergere answer](https://cloud.githubusercontent.com/assets/16018758/26330675/c5f8fa64-3f55-11e7-9f22-7d0b845a9005.JPG)

**Comment by xiodine32** [comment]
Added try catch block with a ViewBag error description. 

![image](https://cloud.githubusercontent.com/assets/792798/26379966/828400ce-4024-11e7-80ad-1bdd73c7dcc2.png)
